language: rust
sudo: false
dist: trusty
matrix:
  fast_finish: true
  include:
    - rust: stable
os:
  - linux
cache:
  apt: true
  directories:
    - target/debug/deps
    - target/debug/build
before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get -qq update; else brew update; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install -y libusb-1.0-0-dev; else brew install libusb; fi
  