[package]
name = "yubico"
version = "0.4.2"
authors = ["Flavio Oliveira <flavio@wisespace.io>", "Pierre-Étienne Meunier <pe@coturnix.fr>"]

description = "Yubikey client API library"
license = "MIT OR Apache-2.0"
keywords = ["yubikey", "authentication", "encryption", "OTP", "Challenge-Response"]
categories = ["authentication"]
repository = "https://github.com/wisespace-io/yubico-rs"
readme = "README.md"

[badges]
travis-ci = { repository = "wisespace-io/yubico-rs" }

[lib]
name = "yubico"
path = "src/lib.rs"

[dependencies]
url = "1.7"
reqwest = {version = "0.8", optional = true}
rand = "0.4"
base64 = "0.9"
threadpool = "1.7"
libusb = "0.2"
bitflags = "1.0.3"

aes-soft = "^0.3"
block-modes = "^0.3"
crypto-mac = "0.7"
hmac = "^0.7"
sha-1 = "^0.8"
subtle = "2.0"

[features]
default = ["online"]
online = ["reqwest"]