[package]
name = "yubico"
version = "0.1.4"
authors = ["Flavio Oliveira <rusty@wisespace.io>"]

description = "Yubikey client API library"
license = "MIT OR Apache-2.0"
keywords = ["HMS", "yubikey", "authentication", "encryption", "OTP"]
categories = ["authentication"]
repository = "https://github.com/wisespace-io/yubico-rs"
readme = "README.md"

[badges]
travis-ci = { repository = "wisespace-io/yubico-rs" }

[lib]
name = "yubico"
path = "src/lib.rs"

[dependencies]
url = "1.4"
hyper = { version = "0.10", default-features = false }
hyper-native-tls = "0.2.2"
rand = "0.3.15"
base64 = "^0.5"
threadpool = "1.3"
rust-crypto = "^0.2"