[package]
name = "yubico"
version = "0.1.1"
authors = ["Flavio Oliveira <rusty@wisespace.io>"]

description = "Yubikey client API library"
license = "MIT"
keywords = ["HMS", "yubikey", "authentication", "encryption", "OTP"]

repository = "https://github.com/wisespace-io/yubico-rs"
readme = "README.md"

[lib]
name = "yubico"
path = "src/lib.rs"

[dependencies]
url = "1.2.3"
hyper = "0.9"
rand = "0.3.15"
base64 = "^0.2"
threadpool = "1.3"
rust-crypto = "^0.2"
