[package]
name = "yubico"
version = "0.2.0"
authors = ["Flavio Oliveira <flavio@wisespace.io>"]

description = "Yubikey client API library"
license = "MIT OR Apache-2.0"
keywords = ["HMS", "yubikey", "authentication", "encryption", "OTP"]
categories = ["authentication"]
repository = "https://github.com/wisespace-io/yubico-rs"
readme = "README.md"

[badges]
travis-ci = { repository = "wisespace-io/yubico-rs" }

[lib]
name = "yubico"
path = "src/lib.rs"

[dependencies]
url = "1.7"
reqwest = "0.8"
rand = "0.4"
base64 = "0.9"
threadpool = "1.7"
rust-crypto = "^0.2"
hidapi = "0.4.1"
clippy = { version = "0.0.186", optional = true }